<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>promise</title>
</head>
<body>

  <script>
    //Promise/A+规范的三种状态
    const PENDING = 'pending'
    const FULFILLED = 'fulfilled'
    const REJECTED = 'rejected'

    class MyPromise {
      constructor (execution) {
        this._status = PENDING

        this._resolveQueue = []
        this._rejectQueue = []

        let _resolve = (val) => {
          if (this._status !== PENDING) return
          this._status = FULFILLED

          /* 记录当前value， 以便后面执行success */
          this._value = val
          while (this._resolveQueue.length) {
            debugger
            let callback = this._resolveQueue.shift()
            callback(val)
          }
        }

        let _reject = (val) => {
          if (this._status !== PENDING) return
          this._status = FULFILLED

          this._value = val
          
          while (this._rejectQueue.length) {
            debugger
            let callback = this._rejectQueue.shift()
            callback(val)
          }
        }
        
        // 如果是异步的那么会先执行then 方法将成功和失败方法加入到各自队列
        execution(_resolve, _reject)
      }
      
      // then方法
      then(success, fail) {

        // 根据规范then参数必须是function, 不是则忽略继续执行后面的then
        typeof success !== 'function' ? success = value => value : null
        typeof fail !== 'function' ? fail = rejectFn = reason => {
          throw new Error(reason instanceof Error? reason.message:reason);
        } : null

        return new MyPromise((resolve, reject) => {
          debugger
          /* 
            val就是resolve的res
            重构success方法，这里得有一个re
           */
          let fulfilledFn = (val) => {
            try {
              let x = success(val)
              x instanceof MyPromise ? x.then(resolve, reject) : resolve(x)
            } catch (err) {
              reject(err)
            }
          }

          let rejectedFn = (error) => {
            try {
              let x = fali(error)
              x instanceof MyPromise ? x.then(resolve, reject) : resolve(x)
            } catch (error) {
              reject(error)
            }
          }
          console.log(this._rejectQueue, this._resolveQueue)

          switch (this._status) {
            case PENDING:
              /* 这是是push到每个then的promise实例中 */
              this._resolveQueue.push(fulfilledFn)
              this._rejectQueue.push(rejectedFn)
              break
            // 当状态已经变为resolve/reject时,直接执行then回调
            case FULFILLED:
              fulfilledFn(this._value)
              break
            case REJECTED:
              rejectedFn(this._value)
              break
          }
        })
      }

      // catch 执行的是then 的第二个回调
      catch(rejectFn) {
        return this.then(undefined, rejectFn)
      }
    }

    /* test */
    var a = new MyPromise ((resolve, reject) => {
      setTimeout(() => {
        console.log(1)
        resolve('success')
      }, 10000)
    }).then((res) => {
      debugger
      return new MyPromise((resolve, reject) => {
        setTimeout(() => {
          debugger
          resolve(2)
        }, 1000)
      })
    }, () => {}).then((res) => {
      debugger
      console.log(3)
      return 3
    }, () => {})
  </script>
</body>
</html>